### ISSUE TITLE
Documentation clarity and accessibility

### ISSUE THREAD

**Issue by dpawson** [tomfaulhaber/autodoc#1]
http://richhickey.github.com/clojure/clojure.core-api.html#clojure.core/numerator
I mistakenly looked for the numerator function in Clojure 1.1
The page states that this is a 1.2 feature.

The text on that page is too small to be clear, to me.
Web Content needs to be accessible not to discriminate.
The Table of contents on that page has next to no contrast.

I wear glasses but am not registered as having low vision.

Please consider Clojure users with less than perfect eye sight.

DaveP

**Comment by puredanger** [comment]
<img width="276" alt="screen shot 2017-11-17 at 9 25 01 am" src="https://user-images.githubusercontent.com/171129/32954631-48aa3266-cb79-11e7-9487-586afe8c7d47.png">

Current impl looks good to me.
