### ISSUE TITLE
Cutting a new release to Clojars

### ISSUE THREAD

**Issue by knusbaum** [tomfaulhaber/autodoc#20]
Is there any scheduled date when a 1.0.0 release of autodoc will be on Clojars? 
The one out there now is very old, and its causing dependency conflicts in my project.

Thanks

**Comment by bensu** [comment]
Hey @knusbaum 

I just noticed that [`1.1.0`](https://clojars.org/autodoc/versions/1.1.0) which might solve your problem.

**Comment by tomfaulhaber** [comment]
Yeah, this is done now. Check out also lein-autodoc to use autodoc with leiningen.
