### ISSUE TITLE
clojure-contrib 1.1.0-master-SNAPSHOT dependency missing

### ISSUE THREAD

**Issue by trptcolin** [tomfaulhaber/autodoc#4]
Looks like build.clojure.org is no longer serving the 1.1.0-master-SNAPSHOT versions, which breaks the dependencies of autodoc 0.7.0.  It seems like changing that dependency to 1.1.0 would be optimal, but I'm not sure how straightforward it would be to backport that, or what commit 0.7.0 is.  I'd be happy to help out in any way I can - just let me know!

See discussions at http://groups.google.com/group/clojure/browse_thread/thread/ce967befa51a89e0, and a more recent one (with Maven commentary from Chas) at http://groups.google.com/group/clojure-dev/browse_thread/thread/149bc60e05cfaa2e

Thanks,
Colin

**Comment by tomfaulhaber** [comment]
This one has long ago been dealt with. I just somehow forgot to close it.
